title: Aikido Terminology
description: Glossary of Japanese aikido terms, techniques, and concepts
url: https://zeiosmb.github.io
baseurl: /aikido-terminology
lang: en

remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

accent_color: rgb(38,139,210)
theme_color: rgb(32,35,42)

menu:
  - title: GitHub
    url: https://github.com/zeiosmb/aikido-terminology

hydejack:
  no_break_layout: false
  no_mark_external: false
  no_search: true
  no_drawer: false

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - vocab.md
  - Gemfile
  - Gemfile.lock
